*** Variables ***
${GOVERNANCE_URL_EXT}  /#
${GOVERNANCE_LOGIN_URL_EXT}  ${GOVERNANCE_URL_EXT}/login
${PROPOSAL_VIEW_URL_EXT}  /proposals
${WALLET_URL_EXT}  /wallet
${KOVAN_GOVERNANCE_URL_EXT}  /governance